# Generated by Django 5.2.6 on 2025-09-20 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('last_date', models.DateField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to=settings.AUTH_USER_MODEL)),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='company_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('since', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('district', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('qualifiication', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='qustionpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qustionpaper', models.FileField(upload_to='')),
                ('answersheet', models.FileField(upload_to='')),
                ('year', models.CharField(max_length=100)),
                ('EXAM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.exam_info')),
                ('GUIDE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.guide')),
            ],
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.CharField(max_length=100)),
                ('discriptio', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('GUIDE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.guide')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('since', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('resume', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('GUIDE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.guide')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='guide_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('review', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('GUIDE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.guide')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='company_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('review', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('COMPANY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='app_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='vaccancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccancy', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('requirement', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('no_of_vaccancy', models.CharField(max_length=100)),
                ('COMPANY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company_table')),
            ],
        ),
        migrations.CreateModel(
            name='appliccation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('interview_date', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
                ('VACCANCY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vaccancy')),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('vedios', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('GUIDE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.guide')),
            ],
        ),
    ]
