# Generated by Django 5.2.6 on 2025-10-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_table',
            name='proof',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
