# Generated by Django 5.2.6 on 2025-11-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_company_table_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliccation',
            name='Resume',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
