# Generated by Django 5.2.6 on 2025-11-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_appliccation_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliccation',
            name='interview_date',
            field=models.DateField(),
        ),
    ]
