# Generated by Django 5.2.6 on 2025-12-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_appliccation_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_review',
            name='rating',
            field=models.FloatField(),
        ),
    ]
