# Generated by Django 5.2.6 on 2025-12-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_company_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide_review',
            name='rating',
            field=models.FloatField(),
        ),
    ]
