# Generated by Django 5.2.6 on 2025-12-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliccation',
            name='interview_date',
            field=models.DateField(null=True),
        ),
    ]
