# Generated by Django 5.2.6 on 2026-02-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_appliccation_interview_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chat',
        ),
    ]
